### ISSUE TITLE
tutorial--introduction的显示和transifex上不一致

### ISSUE THREAD

**Issue by FredWe** [zhsj/python-docs-zh-cn#1]
很多已经翻译的中文段落没有变过来

**Comment by zhsj** [comment]
这是因为编译失败了，可以在 https://github.com/zhsj/python-docs-zh-cn/commits/3.6 看到最近两次同步后面都是 :x: 我待会看下错误原因。

**Comment by zhsj** [comment]
应该是travis 的 bug，把 travis 的缓存清空之后重试了下就好了。
