### ISSUE TITLE
希望参加翻译~

### ISSUE THREAD

**Issue by silkriver** [zhsj/python-docs-zh-cn#3]
我在transifex提交申请了

**Comment by zhsj** [comment]
hi, @silkriver 不好意思之前没看到你的消息。

现在这个 repo 已经迁移到了 https://github.com/python/python-docs-zh-cn 。

欢迎一起来搞事。我大概会在本周之内在 [CPyUG 的邮件列表](https://groups.google.com/forum/#!forum/python-cn)发帖说明的，请再耐心等待一下。
